### ISSUE TITLE
Update to Documenter.jl v1

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/doctheme#2]
TODOs:

1. https://discourse.julialang.org/t/ann-documenter-1-0/103888 
2. https://discourse.julialang.org/t/ann-documenter-1-0/103888/6?u=datseris
3. https://github.com/JuliaDocs/DocumenterTools.jl/issues/82#issuecomment-1737060120 
4. Ensure search bar works, visit https://github.com/JuliaComputing/MultiDocumenter.jl/issues/65#event-10692034044 
5. Utilize the new feature of allowing to expand docstrings twice by using something like
```
```@docs; canonical=false
Prometheus.@time
```
```
6. enable spell check: https://github.com/JuliaDocs/Documenter.jl/blob/master/.github/workflows/SpellCheck.yml

**Comment by kahaaga** [comment]
I'm working on a fix for points 1-3 that allows us to use Documenter v1. One decision to make is:

Since v1, Documenter errors instead of throwing warnings for a range of issues. This new behavior is there to ensure that broken documentation isn't shipped. We've had a bunch of documentation bugs before that could have been caught at the PR stage, so I welcome this change. 

One thing that we need to decide, though, is the following: We've decided that *the public API* is what we document. But we also document internal functions extensively (which is good). But with Documenter v1, the doc build now errors because these internal functions that have docstrings do not show up in any `@docs` block in the documentation. There's three solutions to this: 
- Revert back to the old behavior (warn, not error). *I don't think we should do this*. 
- Create an `internals.md` page where all internal docs go, or
- Set the keyword argument `checkdocs = :exported` to `makedocs`, so that we only care about *exported* functions.

Personally, I favor the last option, because I don't want to clutter the docs unnecessarily. Any thoughts, @Datseris?

**Comment by Datseris** [comment]
option 3 is the way to go, yes I also agree for the change in v1 for error in stead of warn

**Comment by kahaaga** [comment]
> option 3 is the way to go, yes I also agree for the change in v1 for error in stead of warn

That is what I am currently doing in #https://github.com/JuliaDynamics/ComplexityMeasures.jl/pull/341, and it works well - the docs now build.

**Comment by Doublonmousse** [comment]
What is the status of this issue now ? I'm not sure it's clear what's left to do.

I guess it's a sort of "meta" issue for all JuliaDynamics repository to update to v 1 ?

**Comment by Datseris** [comment]
You are right, we can close it! Indeed it is now more of a "meta" issue or reminder. I think the only project I Have to update to the new docs layout is DrWatson.
